### ISSUE TITLE
Version 2.0 review:

### ISSUE THREAD

**Issue by KyleTryon** [cloudqa-io/circle-ci-orb#3]
Hello,

I have identified some items below in need of review:

1. Improper parameterized job executor:
  - https://github.com/accelq/accelq-connect-orb
  - This parameter seems to be tied to the docker "tag" but the name of the parameter is "image"
  - The default parameter value is `cimg/base:stable`
  - Remove `cimg/base:` from executor
 2. Update usage example version.
   - Validate usage example and set version to `2.0`.
   - This next update should result in `2.0.1` being published.
3. Update README.
  - Ensure the links in your readme are valid, and a proper description is provided.
4. There is mention of an "API key" parameter but there is no such parameter listed on the job.
  - If you are expecting an environment variable name to exist, document this here.
  - https://circleci.com/docs/2.0/orb-author-faq/?section=configuration#secure-api-tokens

**Comment by cloudqa-io** [comment]
Made changes to 1, 2, and 3. Please review.
4.Yes, we are expecting an environment variable name(CLOUDQA_API_KEY) to exist.
What needs to be updated/changed on our end?

**Comment by KyleTryon** [comment]
@cloudqa-io Everything looks excellent 👍 . Thank you for the changes. We will continue the process on our end and reach out directly soon.

**Comment by KyleTryon** [comment]
PS: I would recommend added "https://circleci.com/developer/orbs/orb/cloudqa/suite-runner" to the website value for this repo. You may also want to add this link to the Readme.

PPS: Remember you can update the readme without updating the Orb itself by using `[semver:skip]`
